### ISSUE TITLE
Edit Readme pics

### ISSUE THREAD

**Issue by elsowiny** [Black-Axe/Hopes-On-Horizon#2]
> Hi @elsowiny can i help in solving this?
> 
> The readme pictures have some red lines at the bottom, is that what needs to be removed?
> 
> * [ ]  Take a new screenshot
> * [ ]  Edit out the red line and little notification

Yes exactly, but I think @NehaK275  is handling this,

What I think you can do is open an issue here https://github.com/Black-Axe/HopesOnHorizon
and literally do the same thing, I.E remove the redline and maybe the side bar!

_Originally posted by @elsowiny in https://github.com/Black-Axe/AnimatedDevPortfolio/issues/2#issuecomment-1022308116_

**Comment by elsowiny** [comment]
@Ndace-hash

**Comment by Ndace-hash** [comment]
I seem to be having problems installing the project dependencies so that I can run the program on my machine locally
![npmErr](https://user-images.githubusercontent.com/72235686/151889545-a5b8ce2b-b3b6-452e-8841-f303ba72447f.PNG)
.

I was wondering if there is another way I could view the site without having to run it locally? That would be nice

**Comment by elsowiny** [comment]
@Ndace-hash Yes thank you! I will look more into this error and also try to get Docker on here too, but the live site is here for you to view

https://hopesonhorizon.com/
